import { StyleSheet } from 'react-native';

export const colors = {
  background: '#F6F7F3', white: '#FFFFFF', ink: '#183C33',
  muted: '#69766F', green: '#204D3D', lime: '#DCEBB6',
  border: '#E3E8E1', placeholder: '#7B867F',
};

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.background },
  flex: { flex: 1 },
  list: { flex: 1, width: '100%' },
  listContent: { width: '100%', maxWidth: 760, alignSelf: 'center', paddingHorizontal: 22, paddingTop: 20, paddingBottom: 28 },
  brandRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16, flexWrap: 'wrap', marginBottom: 28 },
  companyRow: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  brandMark: { width: 38, height: 38, borderRadius: 12, backgroundColor: colors.green, alignItems: 'center', justifyContent: 'center' },
  brandMarkText: { fontSize: 30, fontWeight: '800', color: colors.lime, marginTop: -4 },
  brandName: { fontSize: 26, fontWeight: '800', letterSpacing: -1, color: colors.ink },
  brandCaption: { color: colors.muted, fontSize: 11, maxWidth: 105, lineHeight: 17 },
  hero: { backgroundColor: colors.green, borderRadius: 26, padding: 25, marginBottom: 32, overflow: 'hidden' },
  heroLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 22 },
  dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.lime },
  heroLabel: { flex: 1, fontSize: 10, fontWeight: '700', letterSpacing: 1.3, color: colors.lime },
  heroTitle: { fontSize: 33, lineHeight: 40, fontWeight: '700', letterSpacing: -1.2, color: colors.white },
  heroDescription: { fontSize: 14, lineHeight: 23, color: '#D5E2D9', marginTop: 16, maxWidth: 440 },
  heroBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12, marginTop: 24 },
  heroTag: { flexShrink: 1, fontSize: 11, color: colors.lime, borderWidth: 1, borderColor: '#54735D', borderRadius: 20, paddingHorizontal: 12, paddingVertical: 8 },
  heroArrow: { color: colors.lime, fontSize: 33 },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  sectionTitle: { flexShrink: 1, fontSize: 21, fontWeight: '700', letterSpacing: -0.5, color: colors.ink },
  count: { color: colors.muted, fontSize: 12, fontWeight: '600', backgroundColor: '#E9EDE5', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 5 },
  sectionDescription: { color: colors.muted, fontSize: 14, marginTop: 7 },
  filters: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginTop: 20, marginBottom: 22 },
  filter: { minHeight: 46, paddingVertical: 12, paddingHorizontal: 18, borderRadius: 24, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, justifyContent: 'center' },
  filterActive: { backgroundColor: colors.green, borderColor: colors.green },
  filterText: { color: colors.muted, fontWeight: '600', fontSize: 13 },
  filterTextActive: { color: colors.white },
  card: { backgroundColor: colors.white, borderRadius: 22, borderWidth: 1, borderColor: colors.border, padding: 22, marginBottom: 15, shadowColor: '#183C33', shadowOpacity: 0.04, shadowOffset: { width: 0, height: 4 }, shadowRadius: 12, elevation: 2 },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  logo: { width: 46, height: 46, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  logoText: { fontSize: 23, fontWeight: '800', letterSpacing: -1 },
  company: { fontSize: 14, fontWeight: '700', color: colors.ink, lineHeight: 21 },
  location: { fontSize: 12, color: colors.muted, marginTop: 3, lineHeight: 18 },
  smallArrow: { fontSize: 25, color: '#9CA89D' },
  cardTitle: { fontSize: 21, fontWeight: '700', letterSpacing: -0.5, color: colors.ink, marginTop: 20, marginBottom: 9 },
  cardDescription: { color: colors.muted, fontSize: 14, lineHeight: 23 },
  cardFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, flexWrap: 'wrap', marginTop: 20, paddingTop: 17, borderTopWidth: 1, borderTopColor: '#EFF1EB' },
  badge: { borderRadius: 8, paddingVertical: 7, paddingHorizontal: 10, alignSelf: 'flex-start' },
  badgeText: { fontSize: 11, fontWeight: '600' },
  smallButton: { backgroundColor: '#EEF3ED', borderRadius: 12, minHeight: 44, paddingHorizontal: 16, paddingVertical: 12, justifyContent: 'center' },
  smallButtonText: { color: colors.green, fontSize: 13, fontWeight: '700' },
  pressed: { opacity: 0.7 },
  footerNote: { color: colors.muted, fontSize: 11, lineHeight: 20, textAlign: 'center', marginTop: 16 },
  pageContent: { width: '100%', maxWidth: 760, alignSelf: 'center', padding: 24, paddingBottom: 36 },
  detailTop: { gap: 16, marginBottom: 28 },
  largeLogo: { width: 70, height: 70, borderRadius: 22, alignItems: 'center', justifyContent: 'center' },
  largeLogoText: { fontSize: 34, fontWeight: '800', letterSpacing: -1 },
  eyebrow: { color: colors.muted, fontSize: 11, fontWeight: '700', letterSpacing: 1.5, marginTop: 12 },
  pageTitle: { fontSize: 34, fontWeight: '700', color: colors.ink, letterSpacing: -1.2, lineHeight: 41, marginTop: 10 },
  metaRow: { flexDirection: 'row', alignItems: 'center', gap: 18, flexWrap: 'wrap' },
  detailCard: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: 22, padding: 23 },
  body: { color: colors.muted, fontSize: 15, lineHeight: 26, marginTop: 14 },
  divider: { height: 1, backgroundColor: colors.border, marginVertical: 25 },
  taskRow: { flexDirection: 'row', gap: 13, alignItems: 'flex-start', marginTop: 20 },
  taskNumber: { width: 28, height: 28, borderRadius: 9, backgroundColor: '#EDF3E8', alignItems: 'center', justifyContent: 'center' },
  taskNumberText: { fontSize: 12, fontWeight: '700', color: colors.green },
  taskText: { flex: 1, fontSize: 14, color: colors.ink, lineHeight: 24 },
  noteCard: { backgroundColor: '#EAF0E2', borderRadius: 18, padding: 20, marginVertical: 22 },
  noteTitle: { fontSize: 14, lineHeight: 22, fontWeight: '700', color: colors.ink },
  noteText: { fontSize: 13, lineHeight: 22, color: '#52674F', marginTop: 7 },
  primaryButton: { backgroundColor: colors.green, borderRadius: 16, minHeight: 56, padding: 17, alignItems: 'center', justifyContent: 'center', width: '100%' },
  primaryButtonText: { color: colors.white, fontSize: 15, fontWeight: '700', textAlign: 'center' },
  helperCentered: { color: colors.muted, fontSize: 12, lineHeight: 20, textAlign: 'center', marginTop: 14 },
  applicationJob: { flexDirection: 'row', alignItems: 'center', gap: 13, padding: 17, borderRadius: 17, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, marginVertical: 25 },
  form: { gap: 22 },
  field: { gap: 9 },
  inputLabel: { fontSize: 14, fontWeight: '600', color: colors.ink },
  input: { borderWidth: 1, borderColor: '#D8E0D6', borderRadius: 14, backgroundColor: colors.white, paddingHorizontal: 16, paddingVertical: 16, minHeight: 54, fontSize: 16, color: colors.ink },
  textArea: { minHeight: 150, lineHeight: 24 },
  helper: { fontSize: 12, color: colors.muted },
  error: { color: '#A13434', fontSize: 13, lineHeight: 21 },
  success: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 18, padding: 28, width: '100%', maxWidth: 560, alignSelf: 'center' },
  successIcon: { width: 88, height: 88, borderRadius: 44, backgroundColor: '#E2EDCD', alignItems: 'center', justifyContent: 'center' },
  successCheck: { fontSize: 42, color: colors.green },
  successTitle: { fontSize: 32, lineHeight: 40, fontWeight: '700', letterSpacing: -1, color: colors.ink, textAlign: 'center' },
  successText: { color: colors.muted, fontSize: 15, lineHeight: 25, textAlign: 'center' },
  empty: { flex: 1, justifyContent: 'center', padding: 28, gap: 24, width: '100%', maxWidth: 560, alignSelf: 'center' },
});
